CREATE TABLE IF NOT EXISTS members (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(60),
  balance DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  total_usage_minutes INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seats (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  seat_no VARCHAR(20) NOT NULL UNIQUE,
  zone VARCHAR(40) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'IDLE'
);

CREATE TABLE IF NOT EXISTS time_packages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  package_minutes INT NOT NULL,
  remaining_minutes INT NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  seat_id BIGINT NOT NULL,
  idempotency_key VARCHAR(64) NOT NULL UNIQUE,
  planned_minutes INT NOT NULL,
  start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_time TIMESTAMP NULL,
  actual_minutes INT NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  session_id BIGINT NULL,
  package_id BIGINT NULL,
  type VARCHAR(24) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  minutes INT NOT NULL DEFAULT 0,
  balance_after DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  description VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operation_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  module_name VARCHAR(120) NOT NULL,
  owner_name VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL,
  metric VARCHAR(40) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
